#! /bin/sh
# PANDA -- a simple transaction monitor
# Copyright (C) 2005-2008  Noboru Saitou
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA

if [ $# -ne 1 ]; then
  echo "Usage: `basename $0` input.ps " 1>&2
  exit 1
fi

: ${TMPDIR=/tmp}
tmpfile=`mktemp ${TMPDIR}/glserver.pnmXXXXXX` || exit 1
trap 'rm -f $tmpfile' 0

gs -q -dBATCH -dMaxBitmap=300000000 -dNOPAUSE -dSAFER -sDEVICE=ppmraw -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -g612x836 -r72x72 -sOutputFile=$tmpfile $1 > /dev/null

if egrep '^%%Orientation: Landscape$' $1 > /dev/null 2>&1; then
    pnmflip -rotate270 $tmpfile | pnmtopng
else
    pnmtopng $tmpfile 
fi
