#! /bin/sh

. ../pathes

TESTBD='paratest'
DIRECTORY='directory1'

./prepare_db.sh 1

echo	"no redirector" 			> "$DBSTUB_LOG"
echo	"1 transaction 100 data" 	>> "$DBSTUB_LOG"
echo	"2 transaction 200 data" 	>> "$DBSTUB_LOG"
echo	"3 transaction 200 data" 	>> "$DBSTUB_LOG"

$DBSTUB --dir $DIRECTORY --bd $TESTBD Test1 >> "$DBSTUB_LOG"

