#! /bin/sh

. ../pathes

TESTBD='paratest'
DIRECTORY='directory1'

./prepare_db.sh 1 2

kill_daemon() {
    pidfile=$1
    signal=$2
    [ -f $pidfile ] && kill -$signal `cat $pidfile` || /bin/true
    rm -f $pidfile
}

$DBREDIRECTOR --dir $DIRECTORY slave > "$DBREDIRECTOR_LOG" &
echo $! > "$DBREDIRECTOR_PID"

echo	"no redirector" 			> "$DBSTUB_LOG"
echo	"1 transaction   0 data" 	>> "$DBSTUB_LOG"
echo	"2 transaction 100 data" 	>> "$DBSTUB_LOG"
echo	"3 transaction 200 data" 	>> "$DBSTUB_LOG"

$DBSTUB --dir $DIRECTORY --bd $TESTBD Test1 >> "$DBSTUB_LOG"

sleep 3

kill_daemon "$DBREDIRECTOR_PID" TERM
