#include	<stdio.h>
#ifdef USE_GNOME
#    include <gnome.h>
#else
#    include <gtk/gtk.h>
#endif

static	void
aplenums_h(void)
{
	printf("\n");
	printf("#define\tAPL_SESSION_NULL\t\t\t%d\n",0);
	printf("#define\tAPL_SESSION_LINK\t\t\t%d\n",1);
	printf("#define\tAPL_SESSION_GET\t\t\t\t%d\n",2);
	printf("#define\tAPL_SESSION_PUT\t\t\t\t%d\n",3);
	printf("#define\tAPL_SESSION_RESEND\t\t\t%d\n",4);
	printf("#define\tAPL_SESSION_END\t\t\t\t%d\n",9);
	printf("\n");
}

static	void
gtkenums_h(void)
{
	printf("\n");
	printf("#define\tWIDGET_STATE_NORMAL\t\t\t%d\n",GTK_STATE_NORMAL);
	printf("#define\tWIDGET_STATE_ACTIVE\t\t\t%d\n",GTK_STATE_ACTIVE);
	printf("#define\tWIDGET_STATE_PRELIGHT\t\t%d\n",GTK_STATE_PRELIGHT);
	printf("#define\tWIDGET_STATE_SELECTED\t\t%d\n",GTK_STATE_SELECTED);
	printf("#define\tWIDGET_STATE_INSENSITIVE\t%d\n",GTK_STATE_INSENSITIVE);
	printf("\n");
}

static	void
mcpenums_h(void)
{
	printf("\n");
	printf("#define\tMCP_OK\t\t\t\t\t\t %d\n",0);
	printf("#define\tMCP_EOF\t\t\t\t\t\t %d\n",1);
	printf("#define\tMCP_NONFATAL\t\t\t\t %d\n",2);
	printf("#define\tMCP_BAD_ARG\t\t\t\t\t%d\n",-1);
	printf("#define\tMCP_BAD_FUNC\t\t\t\t%d\n",-2);
	printf("#define\tMCP_BAD_SQL\t\t\t\t\t%d\n",-3);
	printf("#define\tMCP_BAD_OTHER\t\t\t\t%d\n",-4);
	printf("\n");
}

extern	int
main(
	int		argc,
	char	**argv)
{
	printf("/* This file is generated by enum.c */\n");
	printf("#ifndef\t_INC_ENUM_H\n");
	printf("#define\t_INC_ENUM_H\n");
	aplenums_h();
	gtkenums_h();
	mcpenums_h();
	printf("#endif\n");
	return	0;
}
