/*
 * PANDA -- a simple transaction monitor
 * Copyright (C) 2000-2003 Ogochan & JMA (Japan Medical Association).
 * Copyright (C) 2004-2006 Ogochan.
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include	<stdio.h>

#ifdef	USE_GTK
#include <gtk/gtk.h>
#endif

static	void
aplenums_h(void)
{
	printf("\n");
	printf("#define\tAPL_SESSION_NULL\t\t\t%d\n",0);
	printf("#define\tAPL_SESSION_LINK\t\t\t%d\n",1);
	printf("#define\tAPL_SESSION_GET\t\t\t\t%d\n",2);
	printf("#define\tAPL_SESSION_PUT\t\t\t\t%d\n",3);
	printf("#define\tAPL_SESSION_RESEND\t\t\t%d\n",4);
	printf("#define\tAPL_SESSION_END\t\t\t\t%d\n",9);
	printf("\n");
}

static	void
gtkenums_h(void)
{
	printf("\n");
#ifndef	USE_GTK
	printf("#define\tWIDGET_STATE_NORMAL\t\t\t%d\n",0);
	printf("#define\tWIDGET_STATE_ACTIVE\t\t\t%d\n",1);
	printf("#define\tWIDGET_STATE_PRELIGHT\t\t%d\n",2);
	printf("#define\tWIDGET_STATE_SELECTED\t\t%d\n",3);
	printf("#define\tWIDGET_STATE_INSENSITIVE\t%d\n",4);
#else
	printf("#define\tWIDGET_STATE_NORMAL\t\t\t%d\n",GTK_STATE_NORMAL);
	printf("#define\tWIDGET_STATE_ACTIVE\t\t\t%d\n",GTK_STATE_ACTIVE);
	printf("#define\tWIDGET_STATE_PRELIGHT\t\t%d\n",GTK_STATE_PRELIGHT);
	printf("#define\tWIDGET_STATE_SELECTED\t\t%d\n",GTK_STATE_SELECTED);
	printf("#define\tWIDGET_STATE_INSENSITIVE\t%d\n",GTK_STATE_INSENSITIVE);
#endif
	printf("\n");
}

static	void
mcpenums_h(void)
{
	printf("\n");
	printf("#define\tMCP_OK\t\t\t\t\t\t %d\n",0);
	printf("#define\tMCP_EOF\t\t\t\t\t\t %d\n",1);
	printf("#define\tMCP_NONFATAL\t\t\t\t %d\n",2);
	printf("#define\tMCP_BAD_ARG\t\t\t\t\t%d\n",-1);
	printf("#define\tMCP_BAD_FUNC\t\t\t\t%d\n",-2);
	printf("#define\tMCP_BAD_SQL\t\t\t\t\t%d\n",-3);
	printf("#define\tMCP_BAD_OTHER\t\t\t\t%d\n",-4);
	printf("#define\tMCP_BAD_CONN\t\t\t\t%d\n",-5);
	printf("\n");
}

extern	int
main(
	int		argc,
	char	**argv)
{
	printf("/* This file is generated by enum.c */\n");
	printf("#ifndef\t_INC_ENUM_H\n");
	printf("#define\t_INC_ENUM_H\n");
	aplenums_h();
	gtkenums_h();
	mcpenums_h();
	printf("#endif\n");
	return	0;
}
