/* This file is generated by enum.c */
#ifndef	_INC_ENUM_H
#define	_INC_ENUM_H

#define	APL_SESSION_NULL			0
#define	APL_SESSION_LINK			1
#define	APL_SESSION_GET				2
#define	APL_SYSTEM_END				9

#define	WIDGET_STATE_NORMAL			0
#define	WIDGET_STATE_ACTIVE			1
#define	WIDGET_STATE_PRELIGHT		2
#define	WIDGET_STATE_SELECTED		3
#define	WIDGET_STATE_INSENSITIVE	4

#define	MCP_OK						 0
#define	MCP_EOF						 1
#define	MCP_NONFATAL				 2
#define	MCP_BAD_ARG					-1
#define	MCP_BAD_FUNC				-2
#define	MCP_BAD_SQL					-3
#define	MCP_BAD_OTHER				-4
#define	MCP_BAD_CONN				-5

#endif
